In [2]:
import pandas as pd

In [3]:
df_1 = pd.read_csv('./aggression_parsed_dataset.csv')

df_1 = df_1.drop(columns=['index','ed_label_0','ed_label_1'])
df_1 = df_1.rename(columns={'oh_label': 'label', 'Text': 'text'})

df_1['type'] = df_1['label'].apply(lambda x: 'cyberbullying' if x == 1 else 'not_cyberbullying')

print(df_1.head())

                                                text  label               type
0  `- This is not ``creative``.  Those are the di...      0  not_cyberbullying
1  `  :: the term ``standard model`` is itself le...      0  not_cyberbullying
2    True or false, the situation as of March 200...      0  not_cyberbullying
3   Next, maybe you could work on being less cond...      0  not_cyberbullying
4               This page will need disambiguation.       0  not_cyberbullying

In [4]:
print(df_1['type'].value_counts())

type
not_cyberbullying    101082
cyberbullying         14782
Name: count, dtype: int64

In [5]:
df_2 = pd.read_csv('./attack_parsed_dataset.csv')

df_2 = df_2.drop(columns=['index','ed_label_0','ed_label_1'])
df_2 = df_2.rename(columns={'oh_label': 'label', 'Text': 'text'})

df_2['type'] = df_2['label'].apply(lambda x: 'cyberbullying' if x == 1 else 'not_cyberbullying')

print(df_2.head())

                                                text  label               type
0  `- This is not ``creative``.  Those are the di...      0  not_cyberbullying
1  `  :: the term ``standard model`` is itself le...      0  not_cyberbullying
2    True or false, the situation as of March 200...      0  not_cyberbullying
3   Next, maybe you could work on being less cond...      0  not_cyberbullying
4               This page will need disambiguation.       0  not_cyberbullying

In [6]:
print(df_2['type'].value_counts())

type
not_cyberbullying    102274
cyberbullying         13590
Name: count, dtype: int64

In [7]:
df_3 = pd.read_csv('./kaggle_parsed_dataset.csv')

df_3 = df_3.drop(columns=['index','Date'])
df_3 = df_3.rename(columns={'oh_label': 'label', 'Text': 'text'})

df_3['type'] = df_3['label'].apply(lambda x: 'cyberbullying' if x == 1 else 'not_cyberbullying')

print(df_3.head())

   label                                               text               type
0      1                               "You fuck your dad."      cyberbullying
1      0  "i really don't understand your point.\xa0 It ...  not_cyberbullying
2      0  "A\\xc2\\xa0majority of Canadians can and has ...  not_cyberbullying
3      0  "listen if you dont wanna get married to a man...  not_cyberbullying
4      0  "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...  not_cyberbullying

In [8]:
print(df_3['type'].value_counts())

type
not_cyberbullying    5993
cyberbullying        2806
Name: count, dtype: int64

In [9]:
df_4 = pd.read_csv('./toxicity_parsed_dataset.csv')

df_4 = df_4.drop(columns=['index','ed_label_0','ed_label_1'])
df_4 = df_4.rename(columns={'oh_label': 'label', 'Text': 'text'})

df_4['type'] = df_4['label'].apply(lambda x: 'cyberbullying' if x == 1 else 'not_cyberbullying')

print(df_4.head())

                                                text  label               type
0  This: :One can make an analogy in mathematical...      0  not_cyberbullying
1  `  :Clarification for you  (and Zundark's righ...      0  not_cyberbullying
2                          Elected or Electoral? JHK      0  not_cyberbullying
3  `This is such a fun entry.   Devotchka  I once...      0  not_cyberbullying
4  Please relate the ozone hole to increases in c...      0  not_cyberbullying

In [10]:
print(df_4['type'].value_counts())

type
not_cyberbullying    144324
cyberbullying         15362
Name: count, dtype: int64

In [11]:
df_5 = pd.read_csv('./twitter_parsed_dataset.csv')

df_5 = df_5.drop(columns=['index','Annotation','id'])
df_5 = df_5.rename(columns={'oh_label': 'label', 'Text': 'text'})

df_5 = df_5.dropna(subset=['label'])
df_5['label'] = pd.to_numeric(df_5['label'], errors='coerce').astype(int)

df_5['type'] = df_5['label'].apply(lambda x: 'cyberbullying' if x == 1 else 'not_cyberbullying')

print(df_5.head())

                                                text  label               type
0  @halalflaws @biebervalue @greenlinerzjm I read...      0  not_cyberbullying
1  @ShreyaBafna3 Now you idiots claim that people...      0  not_cyberbullying
2  RT @Mooseoftorment Call me sexist, but when I ...      1      cyberbullying
3  @g0ssipsquirrelx Wrong, ISIS follows the examp...      1      cyberbullying
4                             #mkr No No No No No No      0  not_cyberbullying

In [12]:
print(df_5['type'].value_counts())

type
not_cyberbullying    11501
cyberbullying         5347
Name: count, dtype: int64

In [13]:
df_6 = pd.read_csv('./twitter_racism_parsed_dataset.csv')

df_6 = df_6.drop(columns=['index','Annotation','id'])
df_6 = df_6.rename(columns={'oh_label': 'label', 'Text': 'text'})

df_6['type'] = df_6['label'].apply(lambda x: 'cyberbullying' if x == 1 else 'not_cyberbullying')

print(df_6.head())

                                                text  label               type
0  @AAlwuhaib1977 Muslim mob violence against Hin...      1      cyberbullying
1             @Te4m_NiGhtM4Re http://t.co/5Ih7MkDbQG      0  not_cyberbullying
2  @jncatron @isra_jourisra @AMPalestine Islamoph...      1      cyberbullying
3  Finally I'm all caught up, and that sudden dea...      0  not_cyberbullying
4             @carolinesinders @herecomesfran *hugs*      0  not_cyberbullying

In [14]:
print(df_6['type'].value_counts())

type
not_cyberbullying    11501
cyberbullying         1970
Name: count, dtype: int64

In [15]:
df_7 = pd.read_csv('./twitter_sexism_parsed_dataset.csv')

df_7 = df_7.drop(columns=['index','id','Annotation'])
df_7 = df_7.rename(columns={'oh_label': 'label', 'Text': 'text'})

df_7 = df_7.dropna(subset=['label'])
df_7['label'] = pd.to_numeric(df_7['label'], errors='coerce').astype(int)

df_7['type'] = df_7['label'].apply(lambda x: 'cyberbullying' if x == 1 else 'not_cyberbullying')

print(df_7.head())

                                                text  label               type
0  RT @BeepsS: @senna1 @BeepsS: I'm not sexist bu...      1      cyberbullying
1   There's some very hate able teams this year #MKR      0  not_cyberbullying
2  RT @The_Eccles: "Everyone underestimated us" \...      0  not_cyberbullying
3  RT @NOTLukeDarcy: did @Channel7 or #MKR actual...      0  not_cyberbullying
4  No, you don't. @Shut_Up_Jeff: I thought of a r...      1      cyberbullying

In [16]:
print(df_7['type'].value_counts())

type
not_cyberbullying    11501
cyberbullying         3377
Name: count, dtype: int64

In [17]:
df_8 = pd.read_csv('./youtube_parsed_dataset.csv')

df_8 = df_8.drop(columns=['index','UserIndex','Number of Comments','Number of Subscribers','Membership Duration','Number of Uploads','Profanity in UserID','Age'])
df_8 = df_8.rename(columns={'oh_label': 'label', 'Text': 'text'})

df_8['type'] = df_8['label'].apply(lambda x: 'cyberbullying' if x == 1 else 'not_cyberbullying')

print(df_8.head())

                                                text  label               type
0  Does N.e.bodyelse Hear her Crazy ass Screamin ...      0  not_cyberbullying
1  There are so many things that are incorrect wi...      0  not_cyberbullying
2  3:26 hahah my boyfriend showed this song to me...      1      cyberbullying
3  dick beyonce fuck y a ass hole you are truely ...      1      cyberbullying
4  DongHaeTaemin and Kai ;A; luhansehun and bacon...      0  not_cyberbullying

In [18]:
print(df_8['type'].value_counts())

type
not_cyberbullying    3047
cyberbullying         417
Name: count, dtype: int64

In [19]:
dfs = [df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8]
df = pd.concat(dfs, ignore_index=True)

In [22]:
df = df[df['type'] != 'cyberbullying']
df = df.sample(n=101476, random_state=42)
print(df['type'].value_counts())
df.to_csv('./all_datasets_not_cyberbullying.csv',index=False)

type
not_cyberbullying    101476
Name: count, dtype: int64

In [29]:
df_OLID = pd.read_csv('./datasets/OLID.csv')

df_OLID = df_OLID.drop(columns=['label_C', 'label_B'])

df_OLID = df_OLID.rename(columns={'label_A': 'type'})
df_OLID['type'] = df_OLID['type'].replace({'OFF': 'cyberbullying', 'NOT': 'not_cyberbullying'})
df_OLID['label'] = df_OLID['type'].apply(lambda x: 1 if x == 'cyberbullying' else 0)
df_OLID = df_OLID[df_OLID['label'] == 1].reset_index(drop=True)

df_OLID.head()

                                                text           type  label
0            I be having some weird ass dreams 🤦🏽‍♀️  cyberbullying      1
1      @USER That swole ass dude in GG looks sick af  cyberbullying      1
2  @USER I'm sorry, but your opinion no longer ho...  cyberbullying      1
3  im tired of not being able to fucking sleep , ...  cyberbullying      1
4  Someone could make me a fucking paper airplane...  cyberbullying      1

In [31]:
print(df_OLID['type'].value_counts())

type
cyberbullying    3002
Name: count, dtype: int64

In [37]:
df_cyber = pd.read_csv('./datasets/cyberbullying_tweets.csv')
df_cyber = df_cyber.rename(columns={'tweet_text': 'text','cyberbullying_type':'type'})

df_cyber['type'] = df_cyber['type'].apply(lambda x: 'cyberbullying' if x != 'not_cyberbullying' else 'not_cyberbullying')
df_cyber['label'] = df_cyber['type'].apply(lambda x: 1 if x == 'cyberbullying' else 0)
df_cyber = df_cyber[df_cyber['label'] == 1].reset_index(drop=True)
df_cyber.head()

                                                text           type  label
0  rape is real..zvasiyana nema jokes about being...  cyberbullying      1
1  You never saw any celebrity say anything like ...  cyberbullying      1
2  @ManhattaKnight I mean he's gay, but he uses g...  cyberbullying      1
3  RT @Raul_Novoa16: @AliciaBernardez @Alex_Aim @...  cyberbullying      1
4  Rape is rape. And the fact that I read one pos...  cyberbullying      1

In [38]:
print(df_cyber['type'].value_counts())

type
cyberbullying    39739
Name: count, dtype: int64

In [50]:
df_loyola = pd.read_csv('./datasets/dataset_loyola_university.csv')
df_loyola = df_loyola[['Comment', 'Type']]

df_loyola = df_loyola.rename(columns={'Comment': 'text','Type':'label'})
df_loyola['label'] = df_loyola['label'].fillna(0).astype(int)

df_loyola['type'] = df_loyola['label'].apply(lambda x: 'cyberbullying' if x == 1 else 'not_cyberbullying')
df_loyola = df_loyola[df_loyola['label'] == 1].reset_index(drop=True)
df_loyola.head()

                                                text  label           type
0  @crazycrazycrazy1d lmao just because ur an elo...      1  cyberbullying
1            Ew nay ran skin with white blonde hair       1  cyberbullying
2                                          FUCK YOU       1  cyberbullying
3  Why don't u all shut up and leave me alone! By...      1  cyberbullying
4                    How about u shut up aye _Å½Ã›_       1  cyberbullying

In [51]:
print(df_loyola['type'].value_counts())

type
cyberbullying    1084
Name: count, dtype: int64

In [52]:
df = df[['text', 'type', 'label']]
df_OLID = df_OLID[['text', 'type', 'label']]
df_loyola = df_loyola[['text', 'type', 'label']]
df_cyber = df_cyber[['text', 'type', 'label']]

In [53]:
df = pd.concat([df, df_OLID, df_loyola, df_cyber], ignore_index=True)

In [54]:
print(df.shape)
print(df['type'].value_counts())

(492699, 3)
type
not_cyberbullying    391223
cyberbullying        101476
Name: count, dtype: int64

In [55]:
#undersampling
df_cyberbullying = df[df['type'] == 'cyberbullying']
df_not_cyberbullying = df[df['type'] == 'not_cyberbullying']

df_not_cyberbullying_sampled = df_not_cyberbullying.sample(n=len(df_cyberbullying), random_state=42)

df_balanced = pd.concat([df_cyberbullying, df_not_cyberbullying_sampled], ignore_index=True)

df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

print(df_balanced['type'].value_counts())
print(df_balanced.shape)

type
cyberbullying        101476
not_cyberbullying    101476
Name: count, dtype: int64
(202952, 3)

In [ ]:
df_balanced.to_csv('./all_datasets.csv',index=False)